In [1]:
import torch
print(torch.__version__)  # 설치된 PyTorch 버전 출력
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

if torch.cuda.is_available():
    print(f"GPU 사용 가능: {torch.cuda.get_device_name(0)}")
else:
    print("GPU를 사용할 수 없습니다. CPU를 사용합니다.")

x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y
print("x:", x)
print("y:", y)
print("z:", z)

2.8.0+cpu
False
GPU를 사용할 수 없습니다. CPU를 사용합니다.
x: tensor([[0.3691, 0.6096, 0.1279],
        [0.6550, 0.4162, 0.7734],
        [0.9217, 0.2520, 0.9747]])
y: tensor([[0.1690, 0.1560, 0.2170],
        [0.3368, 0.0324, 0.9282],
        [0.4635, 0.0495, 0.7026]])
z: tensor([[0.5381, 0.7655, 0.3449],
        [0.9917, 0.4486, 1.7016],
        [1.3853, 0.3015, 1.6773]])


In [2]:
x = torch.ones(3, 3)  # 기존 텐서
print(x)
rand_tensor = torch.randint_like(x, 0, 10)  # 기존 크기 유지, 0~9 정수 샘플링

print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[8., 1., 0.],
        [8., 6., 3.],
        [8., 6., 5.]])


In [3]:
tensor = torch.randperm(10)  # 0~9 정수를 무작위 섞기
print(tensor)

tensor([7, 3, 5, 2, 0, 6, 8, 4, 1, 9])


In [4]:
probs = torch.tensor([0.2, 0.8, 0.5, 0.9])  # 0~1 사이 확률값

tensor = torch.bernoulli(probs)  # 각 확률에 따라 0 또는 1 생성

print(tensor)

tensor([0., 1., 1., 1.])


In [5]:
probs = torch.tensor([0.1, 0.2, 0.3, 0.4])  # 각 요소의 선택 확률
tensor = torch.multinomial(probs, 2, replacement=True)  # 2개 선택 (복원 추출)
print(tensor)

tensor([0, 1])


In [6]:
torch.manual_seed(42)  # 시드 고정
print(torch.rand(3, 3))  # 동일한 난수 생성

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [7]:
import torch

# 기존 텐서
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# 일반 연산 (새로운 텐서 반환)
y = x + 10
print("x (원본):", x)  # 원본 텐서 변경 없음
print("y (새로운 텐서):", y)  # 새로운 텐서 생성됨

# 인플레이스 연산
x.add_(10)
print("x (인플레이스 연산 후):", x)  # 기존 텐서가 변경됨

x (원본): tensor([1., 2., 3.])
y (새로운 텐서): tensor([11., 12., 13.])
x (인플레이스 연산 후): tensor([11., 12., 13.])


In [8]:
x = torch.arange(24).view(2, 3, 4)  # 3D 텐서 생성 (배치=2, 행=3, 열=4)

print("x 3차원 :", x)
print("3D Tensor Shape:", x.shape)

xflattened = x.view(2, -1)  # 배치 유지, 나머지는 자동 조정
print("Flattened Shape:", xflattened.shape)

x 3차원 : tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
3D Tensor Shape: torch.Size([2, 3, 4])
Flattened Shape: torch.Size([2, 12])


In [9]:
import torch

x = torch.randn(1, 3, 1, 4)  # (Batch=1, Channels=3, Height=1, Width=4)

x_squeezed = x.squeeze()  # 크기가 1인 차원을 제거

print(x.shape)          # torch.Size([1, 3, 1, 4])
print(x_squeezed.shape) # torch.Size([3, 4])

torch.Size([1, 3, 1, 4])
torch.Size([3, 4])
